name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Version bump to ')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version from commit message
      id: get_version
      run: echo "VERSION=$(echo '${{ github.event.head_commit.message }}' | sed 's/Version bump to //')" >> $GITHUB_OUTPUT

    - name: Create fetch variant
      run: |
        mkdir -p temp_fetch
        cp -r module/general_part/* temp_fetch/
        cp -r module/fetch_variant/* temp_fetch/
        sed '/# LOAD_PIF_FUNCTION_PLACEHOLDER/{
            r module/fetch_variant/load_pif.source.sh
            d
        }' module/service.base.sh > temp_fetch/service.sh
        cd temp_fetch
        rm -f load_pif.source.sh
        zip -r ../autopif-fetch_${{ steps.get_version.outputs.VERSION }}.zip .

    - name: Create selfgen variant
      run: |
        mkdir -p temp_selfgen
        cp -r module/general_part/* temp_selfgen/
        cp -r module/selfgen_variant/* temp_selfgen/
        sed '/# LOAD_PIF_FUNCTION_PLACEHOLDER/{
            r module/selfgen_variant/load_pif.source.sh
            d
        }' module/service.base.sh > temp_selfgen/service.sh
        cd temp_selfgen
        rm -f load_pif.source.sh
        zip -r ../autopif-selfgen_${{ steps.get_version.outputs.VERSION }}.zip .

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: autopif, version ${{ steps.get_version.outputs.VERSION }}
        files: |
          autopif-fetch_${{ steps.get_version.outputs.VERSION }}.zip
          autopif-selfgen_${{ steps.get_version.outputs.VERSION }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up
      run: |
        rm -rf temp_selfgen temp_fetch
        rm -f autopif-fetch_${{ steps.get_version.outputs.VERSION }}.zip
        rm -f autopif-selfgen_${{ steps.get_version.outputs.VERSION }}.zip
